applications/department/urls.py
from django.urls import path
from . import views

app_name = 'department_app'

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('department-new/', views.NewDeparmentView.as_view(), name='department_new'),
    path('department-list/', views.DeparmentListView.as_view(), name='department_list'),
]

applications/person/urls.py
from django.urls import path
from . import views

app_name = 'person_app'

urlpatterns = [
    path('', views.InitialView.as_view(), name = 'initial'),
    path('employee-all/', views.ListAllPerson.as_view(), name='employee_all'),
    path('employee-by-area/<shortname>', views.ListByAreaEmployee.as_view(), name='employee_by_area'),
    path('employee-admin/', views.ListPersonAdmin.as_view(), name='employee_admin'),
    path('employee-search/', views.ListEmployeeByKword.as_view()),
    path('employee-skills/', views.ListEmployeeSkills.as_view()),
    path('employee-detail/<pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employee-add/', views.EmployeeCreateView.as_view(), name='employee_add'),
    path('success/', views.SuccessView.as_view(), name = 'success'),
    path('employee-update/<pk>/', views.EmployeeUpdate.as_view(), name = 'employee_update'),
    path('employee-delete/<pk>/', views.EmployeeDeleteView.as_view(), name = 'employee_delete'),
]

employee_management/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.person.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Employee</li>
      <li><a href="{% url 'person_app:employee_all'%}">List</a></li>
      <li><a href="{% url 'person_app:employee_admin'%}">Administrator</a></li>
      <li><a href="{% url 'department_app:department_list'%}">Department</a></li>
      <li><a href="{% url 'department_app:department_new'%}">New department</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search employee"></li>
      <li><a href="{% url 'person_app:employee_add'%}" class="button">Register</a></li>
    </ul>
  </div>
</div>