applications/person/urls.py
from django.urls import path
from . import views

app_name = 'person_app'

urlpatterns = [
    path('', views.InitialView.as_view(), name = 'initial'),
    path('employee-all/', views.ListAllPerson.as_view(), name='employee_all'),
    path('employee-by-area/<shortname>', views.ListByAreaEmployee.as_view(), name='employee_by_area'),
    path('employee-admin/', views.ListPersonAdmin.as_view(), name='employee_admin'),
    path('employee-search/', views.ListEmployeeByKword.as_view()),
    path('employee-skills/', views.ListEmployeeSkills.as_view()),
    path('employee-detail/<pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employee-add/', views.EmployeeCreateView.as_view(), name='employee_add'),
    path('success/', views.SuccessView.as_view(), name = 'success'),
    path('employee-update/<pk>/', views.EmployeeUpdate.as_view(), name = 'employee_update'),
    path('employee-delete/<pk>/', views.EmployeeDeleteView.as_view(), name = 'employee_delete'),
]

employee_management/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.person.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/person/models.py
from django.db import models
from ckeditor.fields import RichTextField
from applications.department.models import Department


class Skills(models.Model):
    skill = models.CharField('Skill', max_length=50)


    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Employee skills'

    def __str__(self):
        return self.skill

class Person(models.Model):

    POSITIONS = [
        ('EE', 'Electronics Engineer'),
        ('SE', 'Software Engineer'),
        ('ET', 'Electronic Technologist'),
        ('ST', 'Software Technologist'),
    ]

    first_name = models.CharField('Fisrt name', max_length=50)
    last_name = models.CharField('Last name', max_length=50)
    full_name = models.CharField('Full name', max_length=100, blank=True)
    position = models.CharField('Position', max_length=2, choices=POSITIONS)
    deparment = models.ForeignKey(Department, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='employee', blank=True, null=True)
    skill = models.ManyToManyField(Skills)
    curriculum_vitae = RichTextField()




    def __str__(self):
        return self.first_name + ' ' + self.last_name

applications/person/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = (
            'first_name',
            'last_name',
            'position',
            'deparment',
            'skill',
            'image'
        )
        widgets = {
            'skill': forms.CheckboxSelectMultiple()
        }

applications/person/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
    )
from .models import Person
from .forms import PersonForm

class InitialView(TemplateView):
    template_name = 'index.html'


class ListAllPerson(ListView):
    # Lista de todos los empleados
    template_name = 'person/list_all.html'
    paginate_by = 4

    def get_queryset(self):
        key_word = self.request.GET.get('kword', '')
        list_employee = Person.objects.filter(
            full_name__icontains=key_word
            # icontains sirve para buscar caracteres dentro de una lista de carateres
        )
        print('Keyword:', key_word)
        return list_employee


class ListPersonAdmin(ListView):
    # Lista de todos los empleados
    template_name = 'person/employee-admin.html'
    paginate_by = 10
    context_object_name = 'employees'
    model = Person


class ListByAreaEmployee(ListView):
    # Lista de todos los empleados por area
    template_name = 'person/list_by_area.html'
    context_object_name = 'employees'
    def get_queryset(self):
        area = self.kwargs['shortname']
        list_employee = Person.objects.filter(
            deparment__short_name = area
        )
        return list_employee


class ListEmployeeByKword(ListView):
    # Lista de los empleados por palabra clave
    template_name = 'person/list_by_kword.html'
    context_object_name = 'employees'
    def get_queryset(self):
        print('****')
        key_word = self.request.GET.get('kword', )
        list_employee = Person.objects.filter(
            first_name = key_word
        )
        print('Keyword:', key_word)
        return list_employee


class ListEmployeeSkills(ListView):
    template_name = 'skills.html'
    context_object_name = 'skills'
    def get_queryset(self):
        employee = Person.objects.get(id=8)
        return employee.skill.all()


class EmployeeDetailView(DetailView):
    model = Person
    template_name = 'person/detail_employee.html'


class SuccessView(TemplateView):
    model = Person
    template_name = 'success.html'


class EmployeeCreateView(CreateView):
    template_name = 'person/employee-add.html'
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person_app:employee_add')

    def form_valid(self, form):
        employee = form.save(commit=False)
        employee.full_name = employee.first_name + ' ' + employee.last_name
        #print(employee.first_name + ' ' + employee.last_name)
        employee.save()
        return super(EmployeeCreateView, self).form_valid(form)


class EmployeeUpdate(UpdateView):
    template_name = 'person/employee-update.html'
    model = Person
    fields = [
        'first_name',
        'last_name',
        'position',
        'deparment',
        'skill',
        'image' ]
    success_url = reverse_lazy('person_app:employee_admin')

    def post(self, request, *args, **kwargs):
        #guardar datos antes de ser validados
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(EmployeeUpdate, self).form_valid(form)


class EmployeeDeleteView(DeleteView):
    model = Person
    template_name = 'person/employee-delete.html'
    success_url = reverse_lazy('person_app:employee_admin')

templates/person/detail_employee.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ person }}{% endblock %}

{% block content %}

  {% include 'includes/header.html' %}

  <div class="grid-container">
    <h1>Employee Detail</h1>
    <div class="grid-x grid-margin-x align-center">
      <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
        <div class="card-divider">
          {{ person.get_position_display }}
        </div>
        {% if person.image %}
          <img src="{{ person.image.url }}">
        {% else %}
          <img src="{% static 'img/4.jpg' %}">
        {% endif %}
        <div class="card-section">
          <h4>{{ person.full_name }}</h4>
          <p>{{ person.deparment.name }}</p>
          <p><span class="label">Skills:</span></p>
          <ul class="vertical menu">
            {% for i in person.skill.all %}
              <li>{{ i }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
  </div>
  </div>
{% endblock %}

templates/person/employee-add.html
{% extends 'base.html' %}

{% load static %}

{% block title %}EMPLOYEE ADD{% endblock %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Add Employee</h1>
    <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class=" cell medium-6">
        <label>Name:
          {{ form.first_name }}
        </label>
      </div>
      <div class=" cell medium-6">
        <label>Last Name:
          {{ form.last_name }}
        </label>
      </div>
      <div class=" cell medium-6">
        <label>Position:
          {{ form.position }}
        </label>
      </div>
      <div class=" cell medium-6">
        <label>Department:
          {{ form.deparment }}
        </label>
      </div>
      <div class=" cell medium">
        <label>Skills:
          {{ form.skill }}
        </label>
      </div>
      <div class=" cell medium">
        <label>Photo:
          {{ form.image }}
        </label>
      </div>
      <div class=" cell">
        <button type="submit" class="success button">Add</button>
      </div>
    </form>

  </div>
</div>

  {% endblock %}

templates/person/employee-admin.html
{% extends 'base.html' %}

{% load static %}

{% block title %}EMPLOYEE LIST{% endblock %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Employee List</h1>
  </div>
  <div class="cell">
    <table>
      <thead>
        <tr>
          <th width="200">ID</th>
          <th>Name</th>
          <th width="150">Last Name</th>
          <th width="150">Department</th>
            <th width="150">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in object_list %}
        <tr>
          <td>{{ employee.id }}</td>
          <td>{{ employee.first_name }}</td>
          <td>{{ employee.last_name }}</td>
          <td>{{ employee.deparment }}</td>
          <td>
            <a class="button success" href="{% url 'person_app:employee_update' employee.id %}">Edit</a>
          </td>
          <td>
            <a class="button alert" href="{% url 'person_app:employee_delete' employee.id %}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% if is_paginated %}
  <nav aria-label="Pagination">
    <ul class="pagination text-center">
      {% if page_obj.has_previous %}
      <li class="pagination-previous">
        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">
          Previous
        </a>
      </li>
      {% endif %}
      {% for pag in paginator.page_range %}
      {% ifequal pag page_obj.number%}
        <li class="current"><span class="show-for-sr">You're on page</span> {{ pag }}</li>
      {% else %}
        <li><a href="?page={{ pag }}" aria-label="Page 2">{{ pag }}</a></li>
      {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="pagination-next">
        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">
          Next
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>

{% endblock %}

templates/person/employee-delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}EMPLOYEE LIST{% endblock %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Delete Personal Info</h1>
    <form class="cell" method="POST">
      {% csrf_token %}
      <div class="callout secondary">
      <h5>{{ object.full_name }}</h5>
      <p>Are you sure to delete this user?</p>
      <button type="submit" class="button alert">Delete</button>
    </div>

    </form>
  </div>


  </div>

{% endblock %}

templates/person/employee-update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}EMPLOYEE LIST{% endblock %}

{% block content %}

  {% include 'includes/header.html' %}

  <div class="grid-container">
    <h1>Update Personal Info</h1>
    <form class="grid-x grid-margin-x" method="POST">
        {% csrf_token %}
      <div class=" cell medium-6">
        <label>Name:
          {{ form.first_name }}
        </label>
      </div>
      <div class=" cell medium-6">
        <label>Last Name:
          {{ form.last_name }}
        </label>
      </div>
      <div class=" cell medium-6">
        <label>Position:
          {{ form.position }}
        </label>
      </div>
      <div class=" cell medium-6">
        <label>Department:
          {{ form.deparment }}
        </label>
      </div>
      <div class=" cell medium-6">
        <label>Skills:
          {{ form.skill }}
        </label>
      </div>
      <div class=" cell">
        <button type="submit" class="success button">Update</button>
      </div>

    </form>
  </div>

{% endblock %}

templates/person/list_all.html
{% extends 'base.html' %}

{% load static %}

{% block title %}EMPLOYEE LIST{% endblock %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Employee List</h1>
  </div>
  <form class="cell grid-x grid-margin-x" method="GET">
    {% csrf_token %}
    <div class="cell large-7">
      <input type="text" name="kword" value="" id="kword" placeholder="search employee">
    </div>
    <div class="cell large-2">
      <button type="submit" class="success button">Search</button>
    </div>
  </form>
  <div class="cell">
    <table>
      <thead>
        <tr>
          <th width="200">ID</th>
          <th>Name</th>
          <th width="150">Last Name</th>
          <th width="150">Department</th>
            <th width="150">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in object_list %}
        <tr>
          <td>{{ employee.id }}</td>
          <td>{{ employee.first_name }}</td>
          <td>{{ employee.last_name }}</td>
          <td>{{ employee.deparment }}</td>
          <td><a class="button warning" href="{% url 'person_app:employee_detail' employee.id %}">Detail</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% if is_paginated %}
  <nav aria-label="Pagination">
    <ul class="pagination text-center">
      {% if page_obj.has_previous %}
      <li class="pagination-previous">
        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">
          Previous
        </a>
      </li>
      {% endif %}
      {% for pag in paginator.page_range %}
      {% ifequal pag page_obj.number%}
        <li class="current"><span class="show-for-sr">You're on page</span> {{ pag }}</li>
      {% else %}
        <li><a href="?page={{ pag }}" aria-label="Page 2">{{ pag }}</a></li>
      {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="pagination-next">
        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">
          Next
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>

{% endblock %}

templates/person/list_by_area.html
{% extends 'base.html' %}

{% load static %}

{% block title %}EMPLOYEE LIST BY DEPARTMENT{% endblock %}

{% block content %}

  {% include 'includes/header.html' %}


    <div class="grid-container">
    <div class="grid-x">
      <h3 class="cell">Employee Lisy by Area</h3>
      <div class="cell">
        <table>
          <thead>
            <tr>
              <th width="200">ID</th>
              <th>Name</th>
              <th width="150">Last Name</th>
              <th width="150">Department</th>
              <th width="150">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for employee in employees %}
            <tr>
              <td>{{ employee.id }}</td>
              <td>{{ employee.first_name }}</td>
              <td>{{ employee.last_name }}</td>
              <td>{{ employee.deparment }}</td>
              <td><a class="button warning" href="{% url 'person_app:employee_detail' employee.id %}">Detail Employee</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

  </div>


{% endblock %}

templates/person/list_by_kword.html
<!doctype html>
<html lang="en">
  <head>
    <title>Search Employee</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <h1>Search Employee</h1>
    <form class="" method="GET">
      {% csrf_token %}
        <input type="text" name="kword" placeholder="Enter name here" id="kword"/>
        <button type="submit">Search</button>
    </form>
    <ul>
      {% for e in employee %}
        <li>{{ e }}</li>
      {% endfor %}
    </ul>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

templates/person/skills.html
<!doctype html>
<html lang="en">
  <head>
    <title>Employee Skills</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <h1>Employee Skills</h1>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

templates/person/success.html
<!doctype html>
<html lang="en">
  <head>
    <title>success</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <h1>Success View</h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>